version: "3.9"
services:
  build:
    build: .
    volumes:
      - .:/hltb
      - cargo:/root/.cargo/registry
    working_dir: /hltb
    command:
      - /bin/bash
      - --login
      - ./build.sh
volumes:
  cargo: