services:
  build:
    build:
      context: .
      args:
        TARGET_TRIPLE: x86_64-unknown-linux-musl
    platform: linux/amd64
    environment:
      TARGET_TRIPLE: x86_64-unknown-linux-musl
    volumes:
      - .:/hltb
      - cargo:/root/.cargo/registry
    working_dir: /hltb
    command:
      - /bin/bash
      - -c
      - bash ./docker/build.sh
volumes:
  cargo: